// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type UserInput struct {
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
}

type UserResponse struct {
	Result string `json:"result"`
}
